## 1.텐서

In [1]:
import torch
import numpy as np

x = torch.Tensor([[1,2],[3,4]])
x = torch.from_numpy(np.array([[1,2],[3,4]]))

## 2. Autograd

In [2]:
print("[연산 전]\n\n")

x = torch.FloatTensor(2,2)
print(x,"\n")
y = torch.FloatTensor(2,2)
print(y,"\n")
y.requires_grad_(True)

print("[연산 후]\n\n")
z = (x+y) + torch.FloatTensor(2,2)
print(x,"\n")
print(y,"\n")

[연산 전]


tensor([[5.3129e-08, 4.1961e-08],
        [2.1971e-04, 6.6820e+22]]) 

tensor([[-9.8173e-11,  3.0914e-41],
        [-2.4031e+23,  4.5839e-41]]) 

[연산 후]


tensor([[5.3129e-08, 4.1961e-08],
        [2.1971e-04, 6.6820e+22]]) 

tensor([[-9.8173e-11,  3.0914e-41],
        [-2.4031e+23,  4.5839e-41]], requires_grad=True) 



In [3]:
print("[연산 전]\n\n")

x = torch.FloatTensor(2,2)
print(x,"\n")
y = torch.FloatTensor(2,2)
print(y,"\n")
y.requires_grad_(True)

print("[연산 후]\n\n")

with torch.no_grad() :
    z = (x+y) + torch.FloatTensor(2,2)
print(x,"\n")
print(y,"\n")


[연산 전]


tensor([[-2.4031e+23,  4.5839e-41],
        [-2.4031e+23,  4.5839e-41]]) 

tensor([[-2.4031e+23,  4.5839e-41],
        [-2.4031e+23,  4.5839e-41]]) 

[연산 후]


tensor([[-2.4031e+23,  4.5839e-41],
        [-2.4031e+23,  4.5839e-41]]) 

tensor([[-2.4031e+23,  4.5839e-41],
        [-2.4031e+23,  4.5839e-41]], requires_grad=True) 



## 3. feedforward

In [4]:
def linear(x,W,b) : 
    y = torch.mm(x,W) + b
    return y

x = torch.FloatTensor(16,10)
W = torch.FloatTensor(10,5)
b = torch.FloatTensor(5)

y = linear(x,W,b)
print(y.shape)

torch.Size([16, 5])


## 4. nn.Module

In [5]:
import torch.nn as nn

class MyLinear(nn.Module) :
    
    def __init__(self, input_size, output_size) :
        super().__init__()
        
        self.W = torch.FloatTensor(input_size, output_size)
        self.b = torch.FloatTensor(output_size)
    
    def forward(self, x) :
        y = torch.mm(x, self.W) + self.b
        return y      

In [6]:
x = torch.FloatTensor(16,10)
linear = MyLinear(10,5)
y = linear(x)
print(y)
print(y.shape)

tensor([[        nan,         nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,         nan],
        [ 1.4397e+26, -2.7430e-38,  5.8250e-08, -1.8489e-38,  5.8251e-08],
        [        nan,         nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,         nan],
        [ 2.9450e-10, -1.2356e+21,  2.9448e-10,  1.7778e-14,  1.4396e+26],
        [        nan,         nan,         nan,         nan,         nan],
        [-9.7688e-11, -6.4279e-18,  2.2128e+13,  5.1337e-19,  1.4462e+12],
        [        nan,         nan,         nan,         nan,         nan],
        [-9.7688e-11,  3.0914e-41,  2.2228e-01,  3.0914e-41, -9.7675e-11],
        [        nan,         nan,         nan,         nan,         nan],
        [ 1.4375e+26, -2.7388e-38,  5.8161e-08, -1.8461e-38,  5.8161e-08],
        [-9.7688e-11, -1.

In [7]:
params = [p.size() for p in linear.parameters()]
print(params)

[]


In [8]:
import torch.nn as nn

class MyLinear(nn.Module) :
    
    def __init__(self, input_size, output_size) :
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_size, output_size), requires_grad = True)
        self.b = nn.Parameter(torch.FloatTensor(output_size), requires_grad = True)
    
    def forward(self, x) :
        y = torch.mm(x, self.W) + self.b
        return y      

In [9]:
x = torch.FloatTensor(16,10)
linear = MyLinear(10,5)
y = linear(x)
print(y)
print(y.shape)

tensor([[        nan,         nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,         nan],
        [        nan,         nan,         nan,         nan,         nan],
        [-4.3696e+25, -1.0169e+25, -6.6216e+26, -1.6653e+23,  5.9362e-08],
        [        nan,         nan,         nan,         nan,         nan],
        [-4.3789e+11, -1.0191e+11, -6.6356e+12, -1.6689e+09,  1.3623e-19],
        [        nan,         nan,         nan,         nan,         nan],
        [-9.7775e-11,  2.1210e-18, -9.7539e-11,  3.0914e-41,  5.8689e-08],
        [        nan,         nan,         nan,         nan,         nan],
        [ 1.4437e+26, -2.7508e-38,  5.8816e-08, -1.8541e-38,  5.9345e-08],
        [-9.7775e-11,  7.1159e-23, -9.7686e-11,  1.1653e-24,  8.9683e-44],
        [ 1.4468e+12, -8.1886e-06, -4.9368e+20, -8.0601e-17, -8.0718e-17],
        [ 5.8707e-08,  3.1450e-18,  5.8707e-08, -1.8367e-38,  1.3563e-19],
        [-9.7775e-11,  3.

In [10]:
params = [p.size() for p in linear.parameters()]
print(params)

[torch.Size([10, 5]), torch.Size([5])]


In [11]:
import torch.nn as nn

class MyLinear(nn.Module) :
    
    def __init__(self, input_size, output_size) :
        super(MyLinear,self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x) :
        y = self.linear(x)
        return y      

In [12]:
linear = MyLinear(10,5)
print(linear)
params = [p.size() for p in linear.parameters()]
print(params)

MyLinear(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)
[torch.Size([5, 10]), torch.Size([5])]


## 5. back propagation

In [13]:

objective = 100

x = torch.FloatTensor(16,10)
linear = MyLinear(10,5)
y = linear(x)


params = [ parm for parm in linear.parameters()]

print(params)

# print(y.sum())

loss = torch.pow(objective - y.sum(),2)

# print(loss)

loss.backward()

params = [ parm for parm in linear.parameters()]

print(params)

[Parameter containing:
tensor([[-0.0855, -0.1788, -0.0367,  0.2139,  0.0017,  0.1289, -0.2166,  0.0341,
         -0.0184, -0.1835],
        [ 0.2370,  0.2234,  0.0955,  0.1342, -0.0801, -0.0362, -0.0824,  0.0273,
          0.1263, -0.1121],
        [-0.2807,  0.1307, -0.2213, -0.2724,  0.1343,  0.1144,  0.0141, -0.2057,
          0.1483, -0.2492],
        [-0.1546, -0.2279, -0.2016, -0.2175,  0.1029,  0.2460,  0.1697,  0.3103,
          0.1640,  0.2083],
        [-0.2927,  0.2663, -0.0531, -0.2704,  0.0948,  0.2082, -0.0278,  0.0515,
          0.2238,  0.0179]], requires_grad=True), Parameter containing:
tensor([ 0.1908, -0.1352, -0.3060, -0.0046,  0.1296], requires_grad=True)]
[Parameter containing:
tensor([[-0.0855, -0.1788, -0.0367,  0.2139,  0.0017,  0.1289, -0.2166,  0.0341,
         -0.0184, -0.1835],
        [ 0.2370,  0.2234,  0.0955,  0.1342, -0.0801, -0.0362, -0.0824,  0.0273,
          0.1263, -0.1121],
        [-0.2807,  0.1307, -0.2213, -0.2724,  0.1343,  0.1144,  0.0141, 

/home/deokyoung/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


## 6. Train, Eval

- 평가모드, train모드 설정.

In [27]:
linear.eval()

MyLinear(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)

In [28]:
linear.train()

MyLinear(
  (linear): Linear(in_features=10, out_features=5, bias=True)
)

## 7. [example] linear regression model

In [16]:
import random

class MyModel(nn.Module) :
    
    def __init__(self, input_size, output_size) :
        super(MyModel, self).__init__()
        
        self.linear = nn.Linear(input_size, output_size)
        
    def forward(self,x) :
        y = self.linear(x)
        
        return y

In [17]:
def ground_truth(x) : 
    return 3 * x[:,0] + x[:,1]-2*x[:,2]

def train(model, x, y, optim) :

    optim.zero_grad()

    y_hat = model(x)

    loss = ((y-y_hat)**2).sum() / x.size(0)
    
    loss.backward()
    
    optim.step()
    
    return loss.data

        

In [18]:
batch_size = 1
n_epochs = 2
n_iter = 1

model = MyModel(3,1)
optim = torch.optim.SGD(model.parameters(), lr=1e-4, momentum= 0.1)

print(model)

MyModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)


In [19]:
for epoch in range(n_epochs) : 
    avg_loss =0
    
    for i in range(n_iter) :
        x = torch.rand(batch_size, 3)
        y = ground_truth(x.data)
        
        params = [ parm for parm in model.parameters()]
        print(params)
        
        loss = train(model, x, y, optim)
        
        params = [ parm for parm in model.parameters()]
        print(params)
        
        
        
        avg_loss += loss
    avg_loss = avg_loss / n_iter
    
    x_valid = torch.FloatTensor([[.3,.2,.1]])
    y_valid = ground_truth(x_valid.data)
    
    model.eval()
    y_hat = model(x_valid)
    model.train()
    
    print("epoch",epoch,":",avg_loss, y_valid.data[0], y_hat.data[0,0])
    
    if avg_loss < 0.001 :
        break
    

[Parameter containing:
tensor([[-0.0551, -0.0026,  0.1201]], requires_grad=True), Parameter containing:
tensor([0.2168], requires_grad=True)]
[Parameter containing:
tensor([[-0.0547, -0.0024,  0.1203]], requires_grad=True), Parameter containing:
tensor([0.2173], requires_grad=True)]
epoch 0 : tensor(5.2176) tensor(0.9000) tensor(0.2124)
[Parameter containing:
tensor([[-0.0547, -0.0024,  0.1203]], requires_grad=True), Parameter containing:
tensor([0.2173], requires_grad=True)]
[Parameter containing:
tensor([[-0.0543, -0.0021,  0.1204]], requires_grad=True), Parameter containing:
tensor([0.2178], requires_grad=True)]
epoch 1 : tensor(5.4879) tensor(0.9000) tensor(0.2131)


In [20]:
torch.FloatTensor([.3,.2,.1]).size(0)

3

## 8. variable

In [24]:
from torch.autograd import Variable 

x = torch.FloatTensor([[.1,.2,.3]])
Variable(x, volatile = False)

tensor([[0.1000, 0.2000, 0.3000]])

## 2. Autograd